set_scooter_ignition:
  name: Set NIU Scooter Ignition
  fields:
    scooterId:
      description: The scooter ID
      required: True
      example: 0
      default: 0
    ignition:
      description: The ignition state
      required: True
      example: True
      default: False
